Challenge is done
ianaugustosilva/javascript-ninja pull request #4
Opened 2024-01-29 18:06 UTC by ianaugustosilva

In this exercise, I was learn more about methods, functions and literal conditions

2024-01-31 16:39 UTC, priscilaandreani commented on Challenge-04/index.js
> +car.addPeople(2);
Seguindo a sequencia dos exercicios, aqui o carro já tem 5 pessoas 🤔

2024-01-31 16:41 UTC, priscilaandreani reviewed
As lógicas aqui estão certas, mas achei estranho as respostas...

2024-01-31 16:41 UTC, priscilaandreani commented on Challenge-04/index.js
> +car.addPeople(10);
ao adicionar 10 pessoas a mensagem não deveria ser que o limite máximo é 5??

2024-01-31 17:12 UTC, ianaugustosilva commented on Challenge-04/index.js
> +car.addPeople(10);
O limite ainda continua 5
Ele pede pra adicionar 10 pessoas, mas não consigo, pois está dizendo que o limite já é 5, e aí mostra a mensagem dizendo que o carro está cheio

2024-01-31 17:15 UTC, ianaugustosilva commented on Challenge-04/index.js
> +car.addPeople(2);
Hmmm, faz sentido. Em algum momento devo ter zerado a prop, por isso o resultado

2024-02-07 23:09 UTC, priscilaandreani requested changes

2024-02-07 23:09 UTC, priscilaandreani commented on Challenge-04/index.js
> +  quantityPeople: 5,
`quantidadePessoas` - Number - zero por padrão 👁️

2024-02-07 23:09 UTC, priscilaandreani commented on Challenge-04/index.js
> +car.addPeople = function (numberPeoples) {
Aqui a lógica ta um pouquinho errada 👁️ 
Por isso não ta condizente com o resultado final.

2024-02-07 23:09 UTC, priscilaandreani commented on Challenge-04/index.js
> +  if (car.quantityPeople === car.seats && totalPeoples >= car.seats) {
Precisamos verificar primeiro quantas pessoas já estão no carro e se esse número já é maior que a quantidade de assentos. Se sim, o carro está lotado. Se não, só podemos adicionar a quantidade de pesosas no carro até ter o total de 5 pessoas (máximo permitido por carro)

2024-02-14 17:04 UTC, priscilaandreani approved these changes

2024-02-14 17:34 UTC, merged